[
  {
    communityAssociationName: "Bridgeland-Riverside Community Association",
    communityAssociationFacilities: {
      gamesRoom: "No",
      outdoorBBQ: "NA",
      indoorFireplace: "NA",
      mainHallLicensedCapacity: "115",
      meetingRooms: "Yes",
      lounge: "No",
      kitchen: "Yes",
      gym: "No",
      wheelchairAccess: "Yes",
      stage: "NA",
      soundSystem: "NA",
    },
    recreationAmenities: {
      other: "N/A",
      sportsPlayfields: "Yes",
      swimmingPool: "No",
      tennisCourts: "No",
      hockeyRink: "No",
      skatingRink: "No",
    },
    cityQuadrant: "NE",
    programs: {
      youthJustice: "No",
      fitness: "No",
      bingo: "No",
      dance: "No",
      childCare: "No",
      seniorsProgram: "No",
      artClasses: "No",
      sports: "Yes",
    },
    communityAssociationInformation: {
      facilityPhoneNumber: "(403) 263-5755",
      provincialSocietyRegisteredDate: "August 12, 1950",
      communityAssociationWebsite: "brcacalgary.org",
      federalCharityStatusRegistered: "No",
      provincialSocietyRegisteredName:
        "Bridgeland-Riverside Community Association",
      facilityLocatedat: "917 Centre Ave NE  ",
      communityAssociationGeneralEmail: "No",
      facilityFaxNumber: "No",
    },
    communityAssociationBoundaries: {
      north: "7 Avenue; 9A Street; 8 Avenue",
      south: "Bow River",
      east: "Nose Creek",
      west: "1 Street",
    },
  },
  {
    communityAssociationName: "Braeside Community Association",
    recreationAmenities: {
      swimmingPool: "No",
      hockeyRink: "Yes – Outdoor",
      other: "Basketball Courts",
      tennisCourts: "No",
      sportsPlayfields: "Yes",
      skatingRink: "Yes – Outdoor",
    },
    communityAssociationBoundaries: {
      south: "Anderson Road",
      north: "Southland Drive",
      west: "24 Street",
      east: "14 Street",
    },
    programs: {
      sports: "No",
      seniorsProgram: "Yes",
      fitness: "No",
      youthJustice: "Yes",
      dance: "No",
      bingo: "No",
      childCare: "Yes",
      artClasses: "Yes",
    },
    communityAssociationInformation: {
      communityAssociationGeneralEmail: "NA",
      provincialSocietyRegisteredDate: "August 23, 1967",
      communityAssociationWebsite: "NA",
      facilityFaxNumber: "(403) 253-3528",
      facilityLocatedat: "11024 Braeside Drive SW",
      provincialSocietyRegisteredName: "The Braeside Community Association",
      facilityPhoneNumber: "(403) 253-4232",
      federalCharityStatusRegistered: "No",
    },
    cityQuadrant: "SW",
    communityAssociationFacilities: {
      wheelchairAccess: "Yes",
      lounge: "No",
      indoorFireplace: "No",
      soundSystem: "Yes",
      gym: "No",
      meetingRooms: "Yes (Capacity: 25-75)",
      gamesRoom: "No",
      mainHallLicensedCapacity: "240",
      outdoorBBQ: "No",
      stage: "Yes",
      kitchen: "Yes – Standard",
    },
  },
  {
    communityAssociationName:
      "Hounsfield Heights – Briar Hill Community Association",
    communityAssociationInformation: {
      federalCharityStatusRegistered: "No",
      facilityPhoneNumber: "(403) 282-6634",
      provincialSocietyRegisteredName:
        "Hounsfield HeightsBriar Hill Community Association",
      facilityFaxNumber: "N/A",
      provincialSocietyRegisteredDate: "August 28, 1953",
      communityEmail: "admin@hh-bh.ca",
      facilityLocatedat: "1922 - 14 Avenue NW",
      communityAssociationWebsite: "hh-bh.ca",
    },
    communityAssociationFacilities: {
      lounge: "No",
      gym: "Yes",
      wheelchairAccess: "Yes",
      indoorFireplace: "No",
      outdoorBBQ: "No",
      meetingRooms: "Yes (Capacity: 25)",
      stage: "No",
      gamesRoom: "No",
      kitchen: "Yes",
      soundSystem: "No",
      mainHallLicensedCapacity: "100",
    },
    recreationAmenities: {
      sportsPlayfields: "No",
      swimmingPool: "No",
      hockeyRink: "No",
      skatingRink: "Yes – Outdoor",
      tennisCourts: "No",
      other: "N/A",
    },
    cityQuadrant: "NW",
    communityAssociationBoundaries: {
      west: "Crowchild Trail; 12 Avenue; Juniper Road; 22 Street",
      north: "16 Avenue",
      south: "Lane north of 7 Avenue to 19 Street; 8 Avenue",
      east: "14 Street",
    },
    programs: {
      seniorsProgram: "Yes",
      sports: "Yes",
      bingo: "No",
      youthJustice: "No",
      artClasses: "N/A",
      dance: "No",
      fitness: "No",
      childCare: "Yes",
    },
  },
  {
    communityAssociationFacilities: {
      kitchen: "Yes – Commercial",
      mainHallLicensedCapacity: "935",
      lounge: "No",
      meetingRooms: "Yes",
      gamesRoom: "No",
      outdoorBBQ: "No",
      stage: "No",
      soundSystem: "No",
      wheelchairAccess: "Main floor only",
      gym: "No",
      indoorFireplace: "No",
    },
    programs: {
      childCare: "No",
      bingo: "No",
      dance: "No",
      seniorsProgram: "No",
      youthJustice: "No",
      fitness: "No",
      sports: "No",
      artClasses: "N/A",
    },
    cityQuadrant: "NW",
    communityAssociationName: "Bowness Community Association",
    recreationAmenities: {
      swimmingPool: "No",
      other: "N/A",
      skatingRink: "Yes – Indoor",
      tennisCourts: "No",
      hockeyRink: "Yes",
      sportsPlayfields: "Yes",
    },
    communityAssociationInformation: {
      communityEmail: "N/A",
      communityAssociationWebsite: "mybowness.com",
      federalCharityStatusRegistered: "N/A",
      facilityLocatedat: "Facility operated by the City of Calgary",
      provincialSocietyRegisteredDate: "N/A",
      facilityFaxNumber: "(403) 288-8307",
      provincialSocietyRegisteredName: "Bowness Community Association",
      facilityPhoneNumber: "(403) 288-8300",
    },
    communityAssociationBoundaries: {
      west: "101 Street",
      east: "Bow River",
      north: "Bow River",
      south: "16 Avenue; Sarcee Trail; Edworthy Park",
    },
  },
  {
    cityQuadrant: "SW",
    communityAssociationFacilities: {
      soundSystem: "Yes",
      kitchen: "Yes – Commercial",
      stage: "Yes",
      lounge: "No",
      indoorFireplace: "Yes",
      mainHallLicensedCapacity: "220",
      outdoorBBQ: "Yes",
      gamesRoom: "No",
      meetingRooms: "Yes",
      wheelchairAccess: "Yes",
      gym: "No",
    },
    communityAssociationName: "Marda Loop Community Association",
    programs: {
      youthJustice: "No",
      dance: "Yes",
      childCare: "No",
      artClasses: "N/A",
      sports: "Yes",
      seniorsProgram: "No",
      bingo: "No",
      fitness: "No",
    },
    communityAssociationBoundaries: {
      north: "33 Avenue; 20 Street; 26 Avenue",
      east: "14 Street (including River Park and Sandy Beach); Elbow River",
      west: "Crowchild Trail",
      south: "50 Avenue",
    },
    recreationAmenities: {
      other: "Beach Volleyball Courts",
      tennisCourts: "Yes",
      sportsPlayfields: "Yes",
      swimmingPool: "Yes – Outdoor",
      skatingRink: "Yes – Outdoor",
      hockeyRink: "Yes",
    },
    communityAssociationInformation: {
      provincialSocietyRegisteredDate: "21069",
      facilityLocatedat: "3130 - 16 Street SW",
      facilityEmail: "N/A",
      communityAssociationWebsite: "mardaloop.com",
      facilityFaxNumber: "(403) 228-3643",
      provincialSocietyRegisteredName: "Marda Loop Community Association",
      federalCharityStatusRegistered: "No",
      facilityPhoneNumber: "(403) 244-5411",
    },
  },
  {
    programs: {
      childCare: "No",
      sports: "No",
      fitness: "No",
      dance: "No",
      artClasses: "N/A",
      seniorsProgram: "No",
      bingo: "No",
      youthJustice: "No",
    },
    communityAssociationName: "Bankview Community Association",
    cityQuadrant: "SW",
    communityAssociationInformation: {
      communityAssociationWebsite: "bankview.org",
      federalCharityStatusRegistered: "No",
      facilityFaxNumber: "NA",
      facilityLocatedat: "2418 - 17 Street SW",
      facilityEmail: "N/A",
      facilityPhoneNumber: "(403) 244-2544",
      provincialSocietyRegisteredDate: "December 20, 1954",
      provincialSocietyRegisteredName: "Bankview Community Association",
    },
    communityAssociationFacilities: {
      gamesRoom: "No",
      indoorFireplace: "No",
      lounge: "No",
      mainHallLicensedCapacity: "125",
      wheelchairAccess: "Yes",
      soundSystem: "Yes",
      kitchen: "Yes – Standard",
      outdoorBBQ: "Yes",
      gym: "No",
      meetingRooms: "Yes",
      stage: "No",
    },
    recreationAmenities: {
      swimmingPool: "No",
      skatingRink: "Yes",
      tennisCourts: "No",
      other: "N/A",
      hockeyRink: "No",
      sportsPlayfields: "Playground",
    },
    communityAssociationBoundaries: {
      east: "14 Street",
      south: "26 Avenue",
      west: "19 Street; 19A Street (through to 26 Avenue)",
      north: "17 Avenue",
    },
  },
  {
    communityAssociationFacilities: {
      meetingRooms: "Yes",
      indoorFireplace: "No",
      kitchen: "Yes",
      stage: "Yes",
      gamesRoom: "No",
      mainHallLicensedCapacity: "185",
      wheelchairAccess: "Yes",
      soundSystem: "Yes",
      outdoorBBQ: "No",
      gym: "No",
      lounge: "No",
    },
    recreationAmenities: {
      other: "N/A",
      skatingRink: "Yes",
      hockeyRink: "No",
      sportsPlayfields: "No",
      tennisCourts: "No",
      swimmingPool: "No",
    },
    programs: {
      bingo: "No",
      artClasses: "No",
      seniorsProgram: "No",
      dance: "No",
      youthJustice: "No",
      sports: "Yes",
      childCare: "No",
      fitness: "No",
    },
    cityQuadrant: "NE",
    communityAssociationInformation: {
      facilityLocatedat: "228 Whitehorn Road NE",
      facilityFaxNumber: "No",
      facilityPhoneNumber: "(403) 280-2880",
      provincialSocietyRegisteredName: "Whitehorn Community Association",
      provincialSocietyRegisteredDate: "May 19, 1976",
      federalCharityStatusRegistered: "No",
      communityAssociationWebsite: "whitehorncommunity.com",
      communityAssociationGeneralEmail: "info@whitehorncommunity.com",
    },
    communityAssociationBoundaries: {
      north: "McKnight Boulevard",
      south: "32 Avenue",
      east: "52 Street",
      west: "36 Street",
    },
    communityAssociationName: "Whitehorn Community Association",
  },
  {
    communityAssociationName:
      "Palliser – Bayview – Pumphill Community Association",
    communityAssociationBoundaries: {
      west: "24 Street",
      north: "Glenmore Reservoir; Heritage Drive",
      east: "14 Street",
      south: "Southland Drive",
    },
    communityAssociationInformation: {
      provincialSocietyRegisteredName:
        "Palliser-Bayview-Pump Hill Community Association",
      facilityLocatedat: "2323 Palliser Drive SW",
      facilityPhoneNumber: "(403) 281-1908",
      communityAssociationGeneralEmail: "pbpcam@pbpcommunity.ca",
      communityAssociationWebsite: "pbpcommunity.ca",
      facilityFaxNumber: "NA",
      provincialSocietyRegisteredDate: "September 23, 1970",
      federalCharityStatusRegistered: "Yes",
    },
    recreationAmenities: {
      sportsPlayfields: "Yes",
      tennisCourts: "No",
      hockeyRink: "No",
      skatingRink: "Yes – Outdoor",
      other: "N/A",
      swimmingPool: "No",
    },
    communityAssociationFacilities: {
      meetingRooms: "Yes",
      outdoorBBQ: "No",
      gamesRoom: "No",
      stage: "No",
      lounge: "No",
      kitchen: "Yes – Standard",
      gym: "No",
      wheelchairAccess: "Yes",
      soundSystem: "No",
      mainHallLicensedCapacity: "109",
      indoorFireplace: "No",
    },
    programs: {
      dance: "No",
      fitness: "No",
      seniorsProgram: "No",
      artClasses: "N/A",
      sports: "Yes",
      childCare: "Preschool, ages 2-5",
      youthJustice: "No",
      bingo: "No",
    },
    cityQuadrant: "SW",
  },
  {
    cityQuadrant: "NW",
    communityAssociationBoundaries: {
      west: "14 Street",
      north: "John Laurie Boulevard: 40 Avenue",
      east: "9 Street; 38 Avenue (both sides); 10 Street; 32 Avenue; Confederation Park",
      south: "Northmount Drive; Cambrian Drive",
    },
    communityAssociationInformation: {
      communityWebsite: "cambrianheightscommunity.com",
      facilityLocatedat: "600 Northmount Drive NW",
      facilityFaxNumber: "N/A",
      communityEmail: "CHCA_Hall@telus.net",
      provincialSocietyRegisteredDate: "March 5, 1958",
      facilityPhoneNumber: "(403) 284-1175 for facility rentals",
      federalCharityStatusRegistered: "No",
      provincialSocietyRegisteredName:
        "The Cambrian Heights Community Association",
    },
    communityAssociationFacilities: {
      gym: "Yes",
      gamesRoom: "No",
      indoorFireplace: "No",
      lounge: "No",
      kitchen: "Yes – Commercial",
      meetingRooms: "Yes",
      stage: "No",
      outdoorBBQ: "No",
      soundSystem: "No",
      wheelchairAccess: "Yes",
      mainHallLicensedCapacity: "150",
    },
    communityAssociationName: "Cambrian Heights Community Association",
    programs: {
      childCare: "Yes",
      seniorsProgram: "No",
      sports: "No",
      dance: "No",
      artClasses: "N/A",
      youthJustice: "Yes",
      bingo: "No",
      fitness: "Yes",
    },
    recreationAmenities: {
      hockeyRink: "No",
      other: "N/A",
      sportsPlayfields: "Yes",
      swimmingPool: "No",
      skatingRink: "Yes – Outdoor",
      tennisCourts: "No",
    },
  },
  {
    communityAssociationFacilities: {
      wheelchairAccess: "yes",
      indoorFireplace: "yes",
      gamesRoom: "No",
      kitchen: "Yes",
      gym: "yes",
      outdoorBBQ: "yes",
      mainHallLicensedCapacity: "400",
      soundSystem: "Yes",
      stage: "Yes",
      lounge: "Yes",
      meetingRooms: "Yes",
    },
    communityAssociationBoundaries: {
      east: "52 Street",
      west: "36 Street",
      north: "16 Ave",
      south: "Memorial Dr",
    },
    programs: {
      youthJustice: "No",
      bingo: "Yes",
      sports: "Yes",
      artClasses: "No",
      dance: "No",
      seniorsProgram: "Yes",
      fitness: "Yes",
      childCare: "No",
    },
    cityQuadrant: "NE",
    communityAssociationInformation: {
      facilityLocatedat: "636 Marlborough Way NE",
      communityAssociationWebsite: "calgarymarlborough.com",
      communityAssociationGeneralEmail: "info@calgarymarlborough.com",
      facilityPhoneNumber: "403-273-5894",
      facilityFaxNumber: "No",
      provincialSocietyRegisteredName:
        "Calgary Marlborough Community Association",
      provincialSocietyRegisteredDate: "April 10, 1970",
      federalCharityStatusRegistered: "No",
    },
    recreationAmenities: {
      tennisCourts: "No",
      hockeyRink: "No",
      skatingRink: "No",
      sportsPlayfields: "Yes",
      swimmingPool: "No",
      other: "N/A",
    },
    communityAssociationName: "Calgary Marlborough Community Association",
  },
  {
    communityAssociationName: "Strathcona Christie Aspen Community Association",
    communityAssociationFacilities: {
      wheelchairAccess: "No",
      gamesRoom: "No",
      gym: "Yes",
      indoorFireplace: "Yes",
      meetingRooms: "Yes",
      stage: "Yes",
      kitchen: "Yes – Commercial",
      mainHallLicensedCapacity: "240",
      soundSystem: "Yes",
      outdoorBBQ: "No",
      lounge: "Yes",
    },
    programs: {
      bingo: "No",
      sports: "Yes",
      seniorsProgram: "Yes",
      fitness: "Yes",
      childCare: "Yes",
      dance: "Yes",
      artClasses: "N/A",
      youthJustice: "No",
    },
    cityQuadrant: "SW",
    communityAssociationBoundaries: {
      east: "Sarcee Trail",
      north: "Bow Trail",
      west: "Stoney Trail R.O.W.",
      south: "17 Avenue",
    },
    recreationAmenities: {
      other: "N/A",
      skatingRink: "Yes",
      hockeyRink: "Yes – Outdoor",
      sportsPlayfields: "Yes",
      swimmingPool: "No",
      tennisCourts: "Yes",
    },
    communityAssociationInformation: {
      facilityPhoneNumber: "(403) 249-1138",
      facilityFaxNumber: "(403) 249-7811",
      federalCharityStatusRegistered: "No",
      communityAssociationWebsite: "SCACalgary.ca",
      provincialSocietyRegisteredName: "SCA Community Association",
      facilityEmail: "info@SCACalgary.ca",
      facilityLocatedat: "277 Strathcona Drive SW",
      provincialSocietyRegisteredDate: "December 2, 1981",
    },
  },
  {
    programs: {
      dance: "No",
      youthJustice: "No",
      sports: "Yes",
      fitness: "No",
      bingo: "No",
      seniorsProgram: "Yes",
      artClasses: "N/A",
      childCare: "No",
    },
    communityAssociationInformation: {
      provincialSocietyRegisteredName: "Brentwood Community Association",
      facilityFaxNumber: "(403) 284-3951",
      facilityPhoneNumber: "(403) 284-3477",
      communityAssociationWebsite: "brentwoodcommunity.com",
      federalCharityStatusRegistered: "No",
      provincialSocietyRegisteredDate: "December 18, 1963",
      communityEmail: "N/A",
      facilityLocatedat: "Brentwood Sportsplex: 1520B Northmount Drive NW",
    },
    recreationAmenities: {
      tennisCourts: "No",
      sportsPlayfields: "Yes – Soccer",
      skatingRink: "Yes – IndoorOutdoor",
      other: "N/A",
      hockeyRink: "No",
      swimmingPool: "No",
    },
    communityAssociationFacilities: {
      wheelchairAccess: "Yes",
      stage: "No",
      gamesRoom: "No",
      meetingRooms: "Yes",
      outdoorBBQ: "No",
      indoorFireplace: "No",
      lounge: "No",
      soundSystem: "Yes",
      kitchen: "Yes – Commercial",
      mainHallLicensedCapacity: "130",
      gym: "No",
    },
    communityAssociationName: "Brentwood Community Association",
    cityQuadrant: "NW",
    communityAssociationBoundaries: {
      south: "Crowchild Trail",
      north: "John Laurie Boulevard",
      east: "Charleswood Drive; 26 Street; Northmount Drive; Brantford Drive; Brentwood Boulevard",
      west: "Shaganappi Trail",
    },
  },
  {
    recreationAmenities: {
      sportsPlayfields: "Yes",
      swimmingPool: "No",
      other: "N/A",
      hockeyRink: "Yes",
      tennisCourts: "Yes",
      skatingRink: "Yes",
    },
    programs: {
      bingo: "No",
      seniorsProgram: "No",
      artClasses: "No",
      youthJustice: "No",
      childCare: "Yes",
      sports: "Yes",
      fitness: "No",
      dance: "Yes",
    },
    cityQuadrant: "NE",
    communityAssociationBoundaries: {
      north: "16 Avenue",
      south: "CNR mainline",
      east: "East Freeway",
      west: "68 Street",
    },
    communityAssociationName: "Abbeydale Community Association",
    communityAssociationFacilities: {
      kitchen: "Yes",
      mainHallLicensedCapacity: "170",
      wheelchairAccess: "Yes",
      outdoorBBQ: "No",
      lounge: "Yes",
      meetingRooms: "Yes",
      gamesRoom: "No",
      indoorFireplace: "Yes",
      soundSystem: "No",
      stage: "No",
      gym: "No",
    },
    communityAssociationInformation: {
      facilityPhoneNumber: "(403) 248-2229",
      provincialSocietyRegisteredDate: "March 22, 1979",
      facilityFaxNumber: "(403) 248-2880",
      communityAssociationGeneralEmail: "hallmanager@abbeydaleca.com",
      federalCharityStatusRegistered: "No",
      facilityLocatedat: "821 Abbeydale Drive NE",
      provincialSocietyRegisteredName: "Abbeydale Community Association",
      communityAssociationWebsite: "abbeydaleca.com",
    },
  },
  {
    communityAssociationInformation: {
      communityAssociationGeneralEmail: "temp11@telus.net",
      provincialSocietyRegisteredName: "Temple Community Association",
      communityAssociationWebsite: "templecalgary.ca",
      facilityLocatedat: "167 Templegreen RD NE",
      federalCharityStatusRegistered: "No",
      provincialSocietyRegisteredDate: "October 26, 1978",
      facilityFaxNumber: "(403) 293-5441",
      facilityPhoneNumber: "403-280-5466",
    },
    communityAssociationName: "Temple Community Association",
    cityQuadrant: "NE",
    communityAssociationBoundaries: {
      east: "68 Street",
      south: "32 Avenue",
      north: "McKnight Boulevard",
      west: "52 Street",
    },
    communityAssociationFacilities: {
      soundSystem: "Yes",
      wheelchairAccess: "Yes",
      mainHallLicensedCapacity: "250",
      gamesRoom: "No",
      kitchen: "Yes",
      lounge: "No",
      indoorFireplace: "No",
      outdoorBBQ: "No",
      gym: "No",
      meetingRooms: "Yes",
      stage: "Yes",
    },
    recreationAmenities: {
      skatingRink: "Yes",
      hockeyRink: "Yes",
      tennisCourts: "Yes",
      other: "N/A",
      swimmingPool: "No",
      sportsPlayfields: "Yes",
    },
    programs: {
      fitness: "Yes",
      artClasses: "No",
      youthJustice: "Yes",
      seniorsProgram: "No",
      dance: "Yes",
      bingo: "No",
      sports: "Yes",
      childCare: "Yes",
    },
  },
  {
    communityAssociationInformation: {
      communityEmail: "N/A",
      facilityFaxNumber: "None",
      federalCharityStatusRegistered: "No",
      provincialSocietyRegisteredDate: "August 29, 1955",
      facilityLocatedat: "2115 - 20 Avenue NW",
      communityAssociationWebsite: "banfftrailcommunity.ca",
      provincialSocietyRegisteredName: "Banff Trail Community Association",
      facilityPhoneNumber: "(403) 282-2234",
    },
    communityAssociationFacilities: {
      mainHallLicensedCapacity: "91",
      gamesRoom: "No",
      lounge: "No",
      outdoorBBQ: "No",
      kitchen: "Yes – Standard",
      meetingRooms: "Yes",
      stage: "No",
      indoorFireplace: "No",
      soundSystem: "Yes",
      gym: "No",
      wheelchairAccess: "Yes",
    },
    communityAssociationBoundaries: {
      west: "Crowchild Trail",
      north: "Morley Trail; Cochrane Road; Canmore Road",
      east: "19 Street; 24 Avenue; 18 Street",
      south: "16 Avenue",
    },
    recreationAmenities: {
      sportsPlayfields: "Yes",
      hockeyRink: "No",
      skatingRink: "Yes – Outdoor",
      swimmingPool: "No",
      tennisCourts: "No",
      other: "N/A",
    },
    programs: {
      bingo: "No",
      artClasses: "N/A",
      youthJustice: "No",
      seniorsProgram: "Yes",
      dance: "Yes",
      childCare: "No",
      fitness: "No",
      sports: "Outdoor Soccer",
    },
    communityAssociationName: "Banff Trail Community Association",
    cityQuadrant: "NW",
  },
];
